name:                wai-middleware-content-type
version:             0.7.0
github:              "athanclark/wai-middleware-content-type"
license:             BSD3
author:              "Athan Clark"
maintainer:          "athan.clark@gmail.com"
copyright:           "Copyright (c) 2023 Athan Clark"
category:            Web
synopsis:            Route to different middlewares based on the incoming Accept header.

ghc-options: -Wall

extra-source-files:
- README.md

description:         Please see the README on Github at <https://github.com/athanclark/wai-middleware-content-type#readme>

dependencies:
- base >= 4.11 && < 5
- aeson
- blaze-builder
- blaze-html
- bytestring
- clay
- exceptions
- extractable-singleton
- hashable
- http-media
- http-types
- lucid
- mmorph
- monad-control
- monad-control-aligned >= 0.0.2
- monad-logger
- mtl
- resourcet
- shakespeare
- text
- transformers
- transformers-base
- unordered-containers
- urlpath >= 11.0.0
- wai >= 3.2
- wai-logger
- wai-transformers >= 0.1.0

library:
  source-dirs: src

tests:
  wai-middleware-content-type-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -Wall
    - -with-rtsopts=-N
    dependencies:
    - wai-middleware-content-type
    - aeson
    - blaze-builder
    - blaze-html
    - bytestring
    - clay
    - exceptions
    - hashable
    - hspec
    - hspec-wai
    - http-media
    - http-types
    - lucid
    - mmorph
    - monad-control
    - monad-logger
    - mtl
    - resourcet
    - shakespeare
    - text
    - tasty
    - tasty-hspec
    - transformers
    - transformers-base
    - urlpath
    - unordered-containers
    - wai
    - wai-transformers
    - warp
